env:
  gui: false
  max_force: 400.0
  max_torque: 50.0
  friction: 0.5
  spinning_friction: 0.05
  rolling_friction: 0.01
  linear_damping: 0.05
  angular_damping: 0.1
  goal_pos: [2.0, 0.0]
  goal_thresh: 0.2
  short_segment_length: 0.3
  strict_terminal: true
  spin_penalty_k: 0.1
  deviation_tolerance: 0.15

agent:
  lr: 0.0001
  max_action: 1.0
  batch_size: 100
  replay_buffer_max_size: 500000
  gamma: 0.99
  polyak: 0.995
  policy_noise: 0.2
  noise_clip: 1
  policy_delay: 2
  n_iter: 1
  exploration_noise: 0.1

training:
  episodes: 3000
  start_timesteps: 2000
  save_freq: 500
  save_dir: "models/"
  train_segment_mode: "short"
  stage1_threshold: 0.85
  stage1_patience: 20
  stage1_interval: 50
  stage2_threshold: 0.95
  stage2_patience: 20
  stage2_interval: 5
