env:
  gui: false
  max_force: 400.0
  max_torque: 50.0
  friction: 0.5
  linear_damping: 0.05
  angular_damping: 0.1
  goal_pos: [2.0, 0.0]
  goal_thresh: 0.2
  segment_length: 0.3

agent:
  lr: 0.0001
  max_action: 1.0
  batch_size: 100
  replay_buffer_max_size: 500000
  gamma: 0.99
  polyak: 0.995
  policy_noise: 0.2
  noise_clip: 1
  policy_delay: 2
  n_iter: 1
  exploration_noise: 0.1

training:
  episodes: 10000
  start_timesteps: 2000
  save_freq: 500
  save_dir: "models/"
  curriculum:
    # - {until:  500, segment: 0.3}   # short slices  (status-quo)
    # - {until: 1200, segment: 0.6}   # double length
    # - {until: 1700, segment: 1.2}   # half of the 90° arc
    # - {until: 9999, segment: null}  # whole arc afterwards
    - {until: 2000, segment: 0.3}   # short slices  (status-quo)
    - {until: 4500, segment: 0.6}   # double length
    - {until: 7000, segment: 1.2}   # half of the 90° arc
    - {until: 99999, segment: null}  # whole arc afterwards
