env:
  gui: false
  max_force: 10.0
  friction: 0.5
  goal_pos: [2.0, 0.0]
  goal_thresh: 0.1
  max_steps: 200

agent:
  lr: 0.0001
  max_action: 1.0
  batch_size: 100
  replay_buffer_max_size: 500000
  gamma: 0.99
  polyak: 0.995
  policy_noise: 0.2
  noise_clip: 1
  policy_delay: 2
  n_iter: 1
  exploration_noise: 0.1

training:
  episodes: 10000
  start_timesteps: 200
  save_freq: 1000
  save_dir: "models/"